In [1]:
import torch

In [2]:
z=torch.Tensor(4,5)
z

tensor([[ 1.6326e-38,  0.0000e+00, -1.3708e-20,  4.5373e-41,  1.6329e-38],
        [ 0.0000e+00, -1.3707e-20,  4.5373e-41,  1.4946e-38,  0.0000e+00],
        [-1.3708e-20,  4.5373e-41,  1.4946e-38,  0.0000e+00, -1.3707e-20],
        [ 4.5373e-41, -1.5613e-20,  4.5373e-41,  1.6329e-38,  0.0000e+00]])

In [5]:
z.dtype

torch.float32

In [11]:
a = torch.FloatTensor(4,5)
b = torch.FloatTensor([[2,3],[4,5]])
b


tensor([[2., 3.],
        [4., 5.]])

In [12]:
a.dtype

torch.float32

In [13]:
b.dtype

torch.float32

In [14]:
a = torch.IntTensor(4,5)
a

tensor([[-1201836640,       32379,   941244144,           0,    11642056],
        [          0, -1208933552,       32379, -1208931440,       32379],
        [   11642216,           0, -1208930544,       32379,    11642408],
        [          0,    11642056,           0, -1208968400,       32379]],
       dtype=torch.int32)

In [15]:
b=torch.IntTensor([[2,3],[4,5]])
b

tensor([[2, 3],
        [4, 5]], dtype=torch.int32)

In [16]:
y = a+z
y

tensor([[-1.2018e+09,  3.2379e+04,  9.4124e+08,  4.5373e-41,  1.1642e+07],
        [ 0.0000e+00, -1.2089e+09,  3.2379e+04, -1.2089e+09,  3.2379e+04],
        [ 1.1642e+07,  4.5373e-41, -1.2089e+09,  3.2379e+04,  1.1642e+07],
        [ 4.5373e-41,  1.1642e+07,  4.5373e-41, -1.2090e+09,  3.2379e+04]])

In [17]:
y.dtype

torch.float32

In [18]:
torch.add(z,a)


tensor([[-1.2018e+09,  3.2379e+04,  9.4124e+08,  4.5373e-41,  1.1642e+07],
        [ 0.0000e+00, -1.2089e+09,  3.2379e+04, -1.2089e+09,  3.2379e+04],
        [ 1.1642e+07,  4.5373e-41, -1.2089e+09,  3.2379e+04,  1.1642e+07],
        [ 4.5373e-41,  1.1642e+07,  4.5373e-41, -1.2090e+09,  3.2379e+04]])

In [20]:
a = torch.rand(4,5)
a

tensor([[0.9730, 0.4318, 0.6256, 0.9573, 0.5891],
        [0.9776, 0.3237, 0.6348, 0.3974, 0.0726],
        [0.6418, 0.8702, 0.6322, 0.5763, 0.3955],
        [0.8979, 0.4354, 0.9970, 0.2434, 0.8390]])

In [21]:
b = a.numpy()
b

array([[0.97303003, 0.43183023, 0.62563777, 0.9573416 , 0.5890781 ],
       [0.9776302 , 0.32370704, 0.63482136, 0.39739323, 0.07260132],
       [0.64183545, 0.87023956, 0.6321635 , 0.5763264 , 0.39551467],
       [0.89793736, 0.43540013, 0.99697626, 0.24344873, 0.83897173]],
      dtype=float32)

In [23]:
import numpy as np

In [25]:
a = np.ones(5)
b = torch.from_numpy(a)
a

array([1., 1., 1., 1., 1.])

In [26]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [28]:
np.add(a, 1, out=a)
a

array([2., 2., 2., 2., 2.])

In [29]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [30]:
c = b + torch.FloatTensor([1,2,3,4,5])
c

tensor([3., 4., 5., 6., 7.], dtype=torch.float64)

In [33]:
c = c.float()
c.dtype

torch.float32

In [36]:
c=c.double()
c.dtype

torch.float64

In [42]:
x=torch.zeros(2,1,2,1)
x

tensor([[[[0.],
          [0.]]],


        [[[0.],
          [0.]]]])

In [43]:
x.size()

torch.Size([2, 1, 2, 1])

In [44]:
y = torch.squeeze(x)
y

tensor([[0., 0.],
        [0., 0.]])

In [46]:
y.size()

torch.Size([2, 2])

In [51]:
y = torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1])

In [52]:
y = torch.squeeze(y,2)
y.size()

torch.Size([2, 2])

In [58]:
y = torch.rand(2,3)
x = torch.rand(3,2)

x

tensor([[0.9173, 0.9798],
        [0.4142, 0.5457],
        [0.3962, 0.3713]])

In [59]:
y

tensor([[0.6236, 0.5539, 0.4975],
        [0.4790, 0.7694, 0.9918]])

In [60]:
d = torch.matmul(x,y)
d

tensor([[1.0413, 1.2619, 1.4280],
        [0.5196, 0.6492, 0.7472],
        [0.4249, 0.5052, 0.5654]])

In [62]:
d= torch.matmul(y,x)
d

tensor([[0.9985, 1.0979],
        [1.1510, 1.2574]])

In [67]:
x=torch.Tensor([[1,2],[3,4]])
y=torch.Tensor([[2,2],[2,2]])
z=torch.Tensor([[1,2],[3,4]])

In [68]:
torch.eq(x,y)

tensor([[False,  True],
        [False, False]])

In [69]:
torch.eq(x,z)

tensor([[True, True],
        [True, True]])

In [70]:
torch.gt(x,y)

tensor([[False, False],
        [ True,  True]])

In [71]:
torch.lt(x,y)

tensor([[ True, False],
        [False, False]])